@startuml
'https://plantuml.com/sequence-diagram

User -> Server: GET /
Server -> User: redirect to /yyyy-mm-dd

@enduml

@startuml
'https://plantuml.com/sequence-diagram
User -> Server: GET /YYYYMMDD
Server -> Pages: load page [yyyymmdd]
Pages -> YYYYMMDD: render
YYYYMMDD -> API: GET /api/YYYYMM
API -> YYYYMMDD: timeline data

YYYYMMDD -> Timeline: select YYYYMMDD
YYYYMMDD -> API: GET /api/YYYYMMDD
API -> YYYYMMDD: date entry

alt isToday === true
    YYYYMMDD -> DiaryEntry: show textarea
else isToday === false
    alt isFuture === true
        YYYYMMDD -> DiaryEntry: show 404
    end
    YYYYMMDD -> DiaryEntry: show just text of date entry
end

YYYYMMDD -> User: show page
@enduml
